= Instal·lació de Dependències per a un Projecte Vue.js i Configuració de Nginx

== Introducció

Aquest document explica com instal·lar, fer desplegament i configurar les dependències necessàries per a un projecte Vue.js utilitzant `npm`. Les dependències que s'instal·laran són:

- `vue-i18n`: Per a la internacionalització (i18n) en Vue.js.
- `@vitejs/plugin-vue`: Un plugin per a Vite que permet la integració amb Vue.js.
- `vue-router`: Per a gestionar l'enrutament en una aplicació Vue.js.
- `emailjs-com`: Per a enviar correus electrònics directament des del client.

== Instal·lació de Dependències

A continuació, es detallen les ordres necessàries per instal·lar cadascuna de les dependències:

=== 1. Instal·lació de `vue-i18n`

`vue-i18n` és una llibreria que facilita la internacionalització en aplicacions Vue.js. Per instal·lar-la, executa la següent ordre:

[source,bash]
----
npm install vue-i18n
----

=== 2. Instal·lació de `@vitejs/plugin-vue`

`@vitejs/plugin-vue` és un plugin oficial per a Vite que permet la integració amb Vue.js. Per instal·lar-lo, executa la següent ordre:

[source,bash]
----
npm install @vitejs/plugin-vue
----

=== 3. Instal·lació de `vue-router`

`vue-router` és la llibreria oficial d'enrutament per a Vue.js. Per instal·lar-la, executa la següent ordre:

[source,bash]
----
npm install vue-router
----

=== 4. Instal·lació de `emailjs-com`

`emailjs-com` és una llibreria que permet enviar correus electrònics directament des del client sense necessitat d'un backend. Per instal·lar-la, executa la següent ordre:

[source,bash]
----
npm install emailjs-com
----

=== 5. Configuració de Nginx

Primer, cal crear un arxiu de configuració per al frontend a la carpeta `/etc/nginx/sites-available/`. Aquest arxiu definirà com Nginx ha de gestionar les peticions al teu projecte Vue.js.

[source,bash]
----
sudo nano /etc/nginx/sites-available/frontend.conf
----

A continuació, afegeix la configuració següent a l'arxiu:

[source,bash]
----
server {
    listen 80;
    root /var/www/html/recuperacio-fvm-hotels/individual/dist;
    server_name 54.161.94.235 nando-individual.stayin7.info;
    index index.html index.htm;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;  # Redirige todas las rutas a index.html
    }

    location /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_intercept_errors off;
    }

    access_log off;
    error_log /var/log/nginx/pterodactyl.app-error.log error;
    client_max_body_size 100m;
    client_body_timeout 120s;
    sendfile off;

    location ~ /\.ht {
        deny all;
    }
}

----

Guarda i tanca l'arxiu. Ara, crea un enllaç simbòlic a la carpeta `sites-enabled` per habilitar la configuració:

[source,bash]
----
sudo ln -s /etc/nginx/sites-available/frontend.conf /etc/nginx/sites-enabled/
----

Comprova que l'enllaç simbòlic s'ha creat correctament:

[source,bash]
----
ls -l /etc/nginx/sites-enabled/
----


Finalment, reinicia Nginx per aplicar els canvis:

[source,bash]
----
sudo systemctl restart nginx
----

Amb això, les dependències necessàries per a un projecte Vue.js han estat instal·lades i configurades correctament.

=== 3. Compilació del Projecte

Abans de desplegar el projecte, has de compilar-lo per generar els arxius estàtics que serviran amb Nginx.

Accedeix a la carpeta del teu projecte Vue.js:

[source,bash]
----
cd /ruta/al/teu/projecte/web
----

Executa el següent comandament per compilar el projecte:

[source,bash]
----
sudo npm run build
----

Aquest comandament generarà una carpeta `dist` dins del teu projecte, que conté els arxius estàtics compilats.

Per ultim cambie el fitxer .env per cambiar la url de la api:

[source,bash]
----
VUE_APP_API_URL=http://
----

Amb això, el teu projecte Vue.js està llest per ser desplegat i servit amb Nginx.

-link:memoria.adoc[Torna a la Memòria]